"""Generate a professional Drug Development Plan (DDP) PDF from APEX planning output.

Usage:
    from generate_ddp import generate_ddp_pdf
    path = generate_ddp_pdf(
        gene="OSMR", indication="ulcerative colitis",
        verdict="GO", confidence=78.0,
        cso_plan="...", cto_plan="...", cmo_plan="...", cbo_plan="...",
        director_synthesis="...", session_id="abc123"
    )
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

# ---------------------------------------------------------------------------
# Styling constants
# ---------------------------------------------------------------------------

DARK_BLUE = (26, 26, 46)
BODY_BLACK = (0, 0, 0)
GREY = (100, 100, 100)
LIGHT_GREY = (220, 220, 220)
GO_GREEN = (34, 139, 34)
AMBER = (255, 140, 0)
WHITE = (255, 255, 255)

MARGIN = 15
LINE_HEIGHT = 5.5


# ---------------------------------------------------------------------------
# Markdown stripper — removes ## headers and **bold** markers before rendering
# ---------------------------------------------------------------------------

def _strip_markdown(text: str) -> str:
    """Remove common markdown formatting for plain-text PDF rendering."""
    # Remove heading markers (##, ###, etc.)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Remove bold/italic markers (**text**, *text*, __text__, _text_)
    text = re.sub(r"\*{1,3}(.+?)\*{1,3}", r"\1", text)
    text = re.sub(r"_{1,3}(.+?)_{1,3}", r"\1", text)
    # Remove inline code backticks
    text = re.sub(r"`(.+?)`", r"\1", text)
    # Collapse 3+ blank lines into 2
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# ---------------------------------------------------------------------------
# DDP PDF class
# ---------------------------------------------------------------------------

class _DDPPDF(FPDF):
    """Custom FPDF subclass with DDP header/footer."""

    def __init__(self, gene: str, indication: str):
        super().__init__()
        self.gene = gene
        self.indication = indication
        self.set_margins(MARGIN, MARGIN, MARGIN)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        """Thin top rule on non-cover pages."""
        if self.page_no() > 1:
            self.set_draw_color(*LIGHT_GREY)
            self.set_line_width(0.3)
            self.line(MARGIN, 12, self.w - MARGIN, 12)

    def footer(self):
        """Page number centered at bottom; cover page gets custom footer."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GREY)
        if self.page_no() == 1:
            self.cell(0, 10, "Generated by APEX v2.0 | MIT MAS.664 AI Studio", align="C")
        else:
            self.cell(0, 10, f"Page {self.page_no()}", align="C")


# ---------------------------------------------------------------------------
# Section page renderer
# ---------------------------------------------------------------------------

def _render_section(
    pdf: _DDPPDF,
    header: str,
    subheader: str,
    body: str,
) -> None:
    """Render a full section page: header → subheader → rule → body."""
    pdf.add_page()

    # Section header — single line, explicit cursor control
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*DARK_BLUE)
    pdf.set_xy(MARGIN, 20)
    pdf.cell(0, 10, header, align="L", new_x="LMARGIN", new_y="NEXT")

    # Subheader — single line
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(*GREY)
    pdf.set_x(MARGIN)
    pdf.cell(0, 7, subheader, align="L", new_x="LMARGIN", new_y="NEXT")

    # Horizontal rule
    y_rule = pdf.get_y() + 2
    pdf.set_draw_color(*DARK_BLUE)
    pdf.set_line_width(0.5)
    pdf.line(MARGIN, y_rule, pdf.w - MARGIN, y_rule)
    pdf.set_xy(MARGIN, y_rule + 4)

    # Body text — reset x explicitly before multi_cell
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*BODY_BLACK)
    cleaned = _strip_markdown(body) if body else "(No content generated)"
    pdf.set_x(MARGIN)
    pdf.multi_cell(pdf.w - 2 * MARGIN, LINE_HEIGHT, cleaned, align="L")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_ddp_pdf(
    gene: str,
    indication: str,
    verdict: str,
    confidence: float,
    cso_plan: str,
    cto_plan: str,
    cmo_plan: str,
    cbo_plan: str,
    director_synthesis: str,
    session_id: str,
) -> str:
    """Generate a Drug Development Plan PDF from APEX planning output.

    Args:
        gene:               Gene symbol (e.g. "OSMR")
        indication:         Disease indication (e.g. "ulcerative colitis")
        verdict:            Portfolio Director verdict ("GO", "CONDITIONAL GO", "NO-GO")
        confidence:         Confidence score 0–100
        cso_plan:           Elena's Target Validation Strategy section
        cto_plan:           Marcus's Modality & Manufacturing Strategy section
        cmo_plan:           Sarah's Clinical Development Strategy section
        cbo_plan:           James's Commercial & Strategic Assessment section
        director_synthesis: Amara's Executive Summary & Integrated Timeline
        session_id:         APEX session ID (used in filename)

    Returns:
        Absolute path to the generated PDF file.
    """
    # Ensure output directory exists
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    # Build filename (sanitize spaces, lowercase indication)
    safe_indication = indication.lower().replace(" ", "_")
    filename = f"ddp_{gene}_{safe_indication}_{session_id[:8]}.pdf"
    output_path = reports_dir / filename

    # Init PDF
    pdf = _DDPPDF(gene=gene, indication=indication)
    pdf.set_title(f"Drug Development Plan — {gene} for {indication}")
    pdf.set_author("APEX v2.0 | MIT MAS.664 AI Studio")

    # ------------------------------------------------------------------
    # PAGE 1 — Cover
    # ------------------------------------------------------------------
    pdf.add_page()

    # Spacer
    pdf.set_y(40)

    # Main title
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*DARK_BLUE)
    pdf.cell(0, 14, "DRUG DEVELOPMENT PLAN", align="C", new_x="LMARGIN", new_y="NEXT")

    # Gene + indication subtitle
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 10, f"{gene}  |  {indication.title()}", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(12)

    # Verdict badge
    verdict_upper = verdict.upper().strip()
    if "NO-GO" in verdict_upper:
        badge_color = (160, 160, 160)
    elif "CONDITIONAL" in verdict_upper:
        badge_color = AMBER
    else:
        badge_color = GO_GREEN

    # Draw filled rounded rectangle (badge)
    badge_w = 70
    badge_h = 14
    badge_x = (pdf.w - badge_w) / 2
    badge_y = pdf.get_y()

    pdf.set_fill_color(*badge_color)
    pdf.set_draw_color(*badge_color)
    pdf.rect(badge_x, badge_y, badge_w, badge_h, style="F")

    # Verdict text inside badge
    pdf.set_xy(badge_x, badge_y + 2)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*WHITE)
    pdf.cell(badge_w, badge_h - 4, verdict_upper, align="C")

    # Confidence score below badge
    pdf.set_xy(MARGIN, badge_y + badge_h + 6)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 8, f"Confidence Score: {confidence:.0f}%", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(8)

    # Horizontal rule
    pdf.set_draw_color(*LIGHT_GREY)
    pdf.set_line_width(0.4)
    pdf.line(MARGIN + 20, pdf.get_y(), pdf.w - MARGIN - 20, pdf.get_y())
    pdf.ln(8)

    # Date
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*GREY)
    date_str = datetime.now().strftime("%B %d, %Y")
    pdf.cell(0, 8, date_str, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)

    # Prepared by block
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, "Prepared by APEX Executive Team", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "Elena Vasquez (CSO) · Marcus Wei (CTO) · Sarah Okonkwo (CMO) · James Harrington (CBO)", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "Synthesized by Dr. Amara Chen, Portfolio Director", align="C", new_x="LMARGIN", new_y="NEXT")

    # ------------------------------------------------------------------
    # PAGE 2 — Executive Summary (Director synthesis)
    # ------------------------------------------------------------------
    _render_section(
        pdf,
        header="Executive Summary",
        subheader="Dr. Amara Chen, Portfolio Director",
        body=director_synthesis,
    )

    # ------------------------------------------------------------------
    # PAGE 3 — Target Validation Strategy (CSO)
    # ------------------------------------------------------------------
    _render_section(
        pdf,
        header="Section 1: Target Validation Strategy",
        subheader="Dr. Elena Vasquez, Chief Scientific Officer",
        body=cso_plan,
    )

    # ------------------------------------------------------------------
    # PAGE 4 — Modality & Manufacturing Strategy (CTO)
    # ------------------------------------------------------------------
    _render_section(
        pdf,
        header="Section 2: Modality & Manufacturing Strategy",
        subheader="Dr. Marcus Wei, Chief Technology Officer",
        body=cto_plan,
    )

    # ------------------------------------------------------------------
    # PAGE 5 — Clinical Development Strategy (CMO)
    # ------------------------------------------------------------------
    _render_section(
        pdf,
        header="Section 3: Clinical Development Strategy",
        subheader="Dr. Sarah Okonkwo, Chief Medical Officer",
        body=cmo_plan,
    )

    # ------------------------------------------------------------------
    # PAGE 6 — Commercial & Strategic Assessment (CBO)
    # ------------------------------------------------------------------
    _render_section(
        pdf,
        header="Section 4: Commercial & Strategic Assessment",
        subheader="Dr. James Harrington, Chief Business Officer",
        body=cbo_plan,
    )

    # ------------------------------------------------------------------
    # Save
    # ------------------------------------------------------------------
    pdf.output(str(output_path))
    return str(output_path.resolve())
